<?php

/**
 * @file
 * Contains home_task.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function home_task_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the home_task module.
    case 'help.page.home_task':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Home Task Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function home_task_theme($existing, $type, $theme, $path) {

  return [
    'dependency_graph' => [
      'template' => 'dependency_graph',
      'variables' => ['graph' => ''],
    ],
  ];
}
